language: node_js
dist: xenial
node_js:
  - "10"
cache:
  yarn: true

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# upgrade yarn to a more recent version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  - name: "Test"
    script: |
      set -ex
      yarn run tslint
      yarn run prettier
      yarn run typedoc
      yarn run build
deploy:
  - provider: script
    script: ./scripts/publish-packages.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: pages
    skip_cleanup: true
    commiter-from-gh: true
    keep-history: false
    local-dir: dist
    github-token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
